---
client:
  hosts: {{ replace (jsonQuery .Env.VCAP_SERVICES `*[?name=='<<.Env.SERVICE_INSTANCE_NAME>>'].credentials.<<.Env.CREDENTIALS_HOST_FIELD>> | []`) "https://" "" -1}}
  url_prefix:
  use_ssl: {{ jsonQuery .Env.VCAP_SERVICES `*[?name=='<<.Env.SERVICE_INSTANCE_NAME>>'].credentials.<<.Env.CREDENTIALS_HOST_FIELD>>.starts_with(@,'https://') | [0][0]` }}
  certificate:
  client_cert:
  client_key:
  http_auth: "{{ replace (jsonQuery .Env.VCAP_SERVICES `*[?name=='<<.Env.SERVICE_INSTANCE_NAME>>'].credentials.<<.Env.CREDENTIALS_USERNAME_FIELD>> | [0][0]`) `"` "" -1 }}:{{ replace (jsonQuery .Env.VCAP_SERVICES `*[?name=='<<.Env.SERVICE_INSTANCE_NAME>>'].credentials.<<.Env.CREDENTIALS_PASSWORD_FIELD>> | [0][0]`) `"` "" -1 }}"
  timeout: 30
  master_only: False

logging:
  loglevel: INFO
  logfile:
  logformat: default
  blacklist: ['elasticsearch', 'urllib3']